volumes:
  data:
  capnp-secrets:

secrets:
  opam-repo-ci-github-key:
    file: ${SECRETS_DIR}/opam-repo-ci-github-key
  opam-repo-ci-webhook-secret:
    file: ${SECRETS_DIR}/opam-repo-ci-webhook-secret
  opam-repo-ci-ssh-key:
    file: ${SECRETS_DIR}/opam-repo-ci-ssh-key
  mtelvers-cap:
    file: /home/mtelvers/mtelvers.cap

services:
  service:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      --github-app-id 85861
      --github-private-key-file /run/secrets/opam-repo-ci-github-key
      --github-webhook-secret-file /run/secrets/opam-repo-ci-webhook-secret
      --github-account-allowlist ocaml
      --capnp-address=tcp:service:9000
      --submission-service /run/secrets/mtelvers-cap
      --verbosity=warning
    restart: on-failure
    ports:
      - '8080:8080'
    environment:
      - "CI_PROFILE=staging"
      - "CI_DISABLE=macos,freebsd,extras"
      - "CI_DISTROS=debian-13"
      - "CI_POOL=test"
      - "DOCKER_BUILDKIT=1"
      - "PROGRESS_NO_TRUNC=1"
    volumes:
      - 'data:/var/lib/ocurrent'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - 'capnp-secrets:/capnp-secrets'
    secrets:
      - 'opam-repo-ci-github-key'
      - 'opam-repo-ci-webhook-secret'
      - 'opam-repo-ci-ssh-key'
      - 'mtelvers-cap'
    sysctls:
      - 'net.ipv4.tcp_keepalive_time=60'

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    command: >
      --backend /capnp-secrets/opam-repo-ci-admin.cap
      --verbosity=warning
    depends_on:
      - service
    # Wait for the default network to be created
    restart: on-failure
    ports:
      - '8090:8090'
    volumes:
      - 'capnp-secrets:/capnp-secrets:ro'
    sysctls:
      - 'net.ipv4.tcp_keepalive_time=60'
