(library
 (name opam_repo_ci)
 (package opam-repo-ci-api)
 (modules coordinator db github_status monitor slurm)
 (preprocess
  (pps ppx_deriving.std ppx_deriving_yojson))
 (libraries
  logs
  ppx_deriving_yojson.runtime
  ocaml-version
  fpath
  opam-client
  lwt
  lwt.unix
  sqlite3
  uri
  yojson
  cohttp
  cohttp-lwt
  cohttp-lwt-unix
  ocaml-slurm))
